apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logping
  name: file-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      # volumes: # Define volume
      #   - name: shared-file
      #     emptyDir: {}
      containers:
        - name: logoutput
          image: mahk00/logoutput:2.0.7
          # volumeMounts: # Mount volume
          # - name: shared-file
          #   mountPath: /usr/src/app/files
        - name: writerapp
          image: mahk00/writerapp:0.1
          # volumeMounts: # Mount volume
          # - name: shared-file
          #   mountPath: /usr/src/app/files
