apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-dep
  namespace: logping

spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      # volumes: # Define volume
      #   - name: shared-file
      #     emptyDir: {}
      containers:
        - name: logoutput
          image: mahk00/logoutput:2.2.1
          # command: [ "/bin/sh", "-c", "env" ]
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: message
          volumeMounts:
          - name: foo
            mountPath: "/etc/foo"
            readOnly: true
          readinessProbe: 
            initialDelaySeconds: 15
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          # volumeMounts: # Mount volume
          # - name: shared-file
          #   mountPath: /usr/src/app/files
        - name: writerapp
          image: mahk00/writerapp:0.1
          # volumeMounts: # Mount volume
          # - name: shared-file
          #   mountPath: /usr/src/app/files
      volumes:
      - name: foo
        configMap:
          name: env-config  
