apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: logping

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: mahk00/ping-pong:2.7.9
          env:
          - name: USERNAME # ENV name passed to container
            valueFrom:
              secretKeyRef:
                name: db-uri
                key: USERNAME # ENV name in the secret
          - name: PASSWORD # ENV name passed to container
            valueFrom:
              secretKeyRef:
                name: db-uri
                key: PASSWORD # ENV name in the secret