apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project-kub
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: shared-file
          persistentVolumeClaim:
            claimName: file-claim
      containers:
        - name: todo
          image: mahk00/todo:1.0.3
          volumeMounts:
            - name: shared-file
              mountPath: /usr/src/app/files
        - name: todo-backend
          image: mahk00/todo-backend:2.7.5
          env:
          - name: USERNAME # ENV name passed to container
            valueFrom:
              secretKeyRef:
                name: db-uri
                key: USERNAME # ENV name in the secret
          - name: PASSWORD # ENV name passed to container
            valueFrom:
              secretKeyRef:
                name: db-uri
                key: PASSWORD # ENV name in the secret