apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project-kub
  name: file-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi