apiVersion: ENC[AES256_GCM,data:8e8=,iv:LhSzcr7hH68ggtxW7kexLSgVcTcF0aYGLf6/rnmqESY=,tag:OybC3Q8aoyogHbyPUhWc8w==,type:str]
kind: ENC[AES256_GCM,data:kQzkhpca,iv:eO3rysDyRff+mBj7xxfXqzQr4/XCjUTo81qrwm94eAA=,tag:giSprxohlm1b6j+WsJQm2w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:no3rY6Ki,iv:4+1Rc31I0LQltMr6nR+WxbloNJ5KwYzrATrnDn4a6wc=,tag:GvmrwLPvu4Gqx9bi8vZpRg==,type:str]
data:
    USERNAME: ENC[AES256_GCM,data:zkAergVN0JVa/rX7,iv:hZApzMIgDMcmPv5R8sAhZYtJIg+iG+aoSK1NUZbYRTs=,tag:mSRQLEDA8Fm2xSgPC/HQZQ==,type:str]
    PASSWORD: ENC[AES256_GCM,data:gvJKaMjbW9ScG2Pv,iv:1OKnQRM4aNPQi+FfTdprAT5HswoBEuU9bIJUPNM5aiM=,tag:Lm/eHNxivlJl220T4npFzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ahshd5n6q0mjth0zfzcqtsg4s8j20kyax4ynjcjw32lpsfks4xsjzmy59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTWJWK0dINUJMWnV6RUQy
            d0RMcUtHZ2tubFplRkFOSHlNRzV4L2gvWnprCmRkWDZ3dmNMeGdadXJldEdMdFpS
            UWh3a1Z3bk43aFBsMUx4ZGJkbzhqREkKLS0tIGNzWGFQbjZvOGdJSHAvdS9VKzRY
            UjRDeEtzRFVDSEtDelZNanZEYW1kRUEKDafch07GgoJrAZ/YWONVBN+s+sODYNPX
            I6oKAOYPPhFiZuTxyOVU5qP/O8XX58MwJxQg0QSyXLD/RQTtyfir6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-29T15:25:46Z"
    mac: ENC[AES256_GCM,data:AJY4rkwEys4uPQ2hPnZwam9ETt1dZ66V3pr2OHmgnR+BmKKC2JrdMJA7VCoYJ0D0mLTU5yEXPE6B7oR7YrsPEszHW6Y2B96eqNgECmRjtU4VY6mLBSAvIwoXL1MOwzsE1U4moKcuNyOn/5BtgNF3Y0NDBiYkjLZr/fZGosjI3Rw=,iv:wr7f+MGv+iQTa6Rwje2cktrjadLU57NqZ4jvex4izXU=,tag:Iq9qJqW2OTyL1zXFyd35Hg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
